/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6 */

#include "messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Command, Command, AUTO)


PB_BIND(Status, Status, AUTO)


PB_BIND(Pos, Pos, AUTO)



