/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MESSAGES_PB_H_INCLUDED
#define PB_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Command {
    bool reset;
} Command;

typedef struct _Pos {
    float x;
    float y;
} Pos;

typedef struct _Status {
    bool has_heading;
    float heading;
    bool has_pos;
    Pos pos;
} Status;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Command_init_default                     {0}
#define Status_init_default                      {false, 0, false, Pos_init_default}
#define Pos_init_default                         {0, 0}
#define Command_init_zero                        {0}
#define Status_init_zero                         {false, 0, false, Pos_init_zero}
#define Pos_init_zero                            {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Command_reset_tag                        1
#define Pos_x_tag                                1
#define Pos_y_tag                                2
#define Status_heading_tag                       3
#define Status_pos_tag                           4

/* Struct field encoding specification for nanopb */
#define Command_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     reset,             1)
#define Command_CALLBACK NULL
#define Command_DEFAULT NULL

#define Status_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FLOAT,    heading,           3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pos,               4)
#define Status_CALLBACK NULL
#define Status_DEFAULT NULL
#define Status_pos_MSGTYPE Pos

#define Pos_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, FLOAT,    x,                 1) \
X(a, STATIC,   REQUIRED, FLOAT,    y,                 2)
#define Pos_CALLBACK NULL
#define Pos_DEFAULT NULL

extern const pb_msgdesc_t Command_msg;
extern const pb_msgdesc_t Status_msg;
extern const pb_msgdesc_t Pos_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Command_fields &Command_msg
#define Status_fields &Status_msg
#define Pos_fields &Pos_msg

/* Maximum encoded size of messages (where known) */
#define Command_size                             2
#define MESSAGES_PB_H_MAX_SIZE                   Status_size
#define Pos_size                                 10
#define Status_size                              17

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
